title: AVAnnotate Documentation
description: This repository is home to documentation and tutorials for using AVAnnotate. 
theme: just-the-docs

url: https://github.com/saamturner/ava_documentation

# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/just-the-docs.png"


aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
