title: AVAnnotate Documentation
description: This repository is home to documentation and tutorials for using AVAnnotate. 
theme: just-the-docs

url: https://github.com/saamturner/ava_documentation

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
